### ISSUE TITLE
Implicit service injection fails in unit tests for dasherized names

### ISSUE THREAD

**Issue by elwayman02** [switchfly/ember-test-helpers#108]
Given a service `foo-bar`, a route with `fooBar: Ember.inject.service()`, and a unit test with `needs: ['service:foo-bar']`, the test blows up and fails to find the injected service via implicit name lookup.

**Comment by elwayman02** [comment]
If you explicitly inject, it works...ie `fooBar: Ember.inject.service('foo-bar')`

**Comment by rwjblue** [comment]
Based on https://github.com/rwjblue/ember-qunit/issues/199, I think this may be related to resolver shenanigans (and not directly related to services themselves).

**Comment by rwjblue** [comment]
I've got a solution that I am working on for this, hopefully will have a PR ready shortly...
