### ISSUE TITLE
How should mutliple render calls in one test behave?

### ISSUE THREAD

**Issue by dschmidt** [switchfly/ember-test-helpers#111]
I just generated a component integration test for one of my components which has a hardcoded elementId (F*ck me, right?) and the test exploded into my face with
```Assertion Failed: Attempted to register a view with an id already in use: myComponentName```
because of the two render calls (block and non-block form).

@rwjblue on Slack:
> Should we allow multiple `this.render` calls in one test, and if we do should we teardown the prior one before doing another?
> the answers do not seem obvious to me
> I guess I would lean towards cleaning up if a `this.render` was already run....
> if you care and have time, i'd love an issue in ember-test-helpers for this
> it seems somewhat edge-casey but seems valuable to get it right

**Comment by rwjblue** [comment]
Thanks for reporting!  

@ef4 / @dgeb - Thoughts on this?

**Comment by dschmidt** [comment]
FWIW it's perfectly possible to have two tests invoke this very same component.
It seems questionable to me if there's value in mixing both render types into one test or if it wasn't a better idea to separate them by default in the component-test blueprint.

**Comment by rwjblue** [comment]
@dschmidt - Yes, the default blueprint is definitely *odd* at best (having both block and blockless in the same test).  We should definitely fix that (perhaps @trabus recalls why we went this specific way).

**Comment by trabus** [comment]
I believe the intent was actually to show both forms for the consumer to pick one or the other, we obviously weren't clear about it.

**Comment by ef4** [comment]
I think a second `render` call should properly tear down the first one first. There seems to be no downside to that, and it will Just Work as expected.

**Comment by yaymukund** [comment]
👍  this should be fixed. 

Cleanup failures are really annoying to debug because it effectively leaks state into subsequent tests.

**Comment by rwjblue** [comment]
https://github.com/switchfly/ember-test-helpers/pull/147 added the ability to call `clearRender` as needed, but did not add guards or automatically call `clearRender` when multiple `this.render` calls are made.

In theory I am fine with either, but kinda lean towards automatically calling `clearRender` on any subsequent `this.render` calls (since multiple `this.render` calls "works" today).

**Comment by rwjblue** [comment]
Should be resolved by https://github.com/switchfly/ember-test-helpers/pull/155.
