### ISSUE TITLE
Injecting services for component integration tests doesn't seem to work

### ISSUE THREAD

**Issue by devinus** [switchfly/ember-test-helpers#114]
The following code using `this.inject.service` never seems to inject the service into the component before trying to render.

```
/* jshint expr:true */
import { expect } from 'chai';
import {
  describeComponent,
  it
} from 'ember-mocha';
import hbs from 'htmlbars-inline-precompile';

describeComponent(
  'provider-options',
  'Integration: ProviderOptionsComponent',
  {
    integration: true
  },
  function() {
    it('renders', function() {
      // Set any properties with this.set('myProperty', 'value');
      // Handle any actions with this.on('myAction', function(val) { ... });
      // Template block usage:
      // this.render(hbs`
      //   {{#provider-options}}
      //     template content
      //   {{/provider-options}}
      // `);

      this.inject.service('i18n'); // <= This doesn't seem to inject the i18n service
      this.render(hbs`{{provider-options}}`);
      expect(this.$()).to.have.length(1);
    });
  }
);
```

**Comment by rwjblue** [comment]
Use the service name only (not the type and the name):

    this.inject.service('i18n')

**Comment by devinus** [comment]
I'm sorry, I actually was using `this.inject.service('i18n')` and filed the issue with the code after a small edit. But `this.inject.service('i18n')` doesn't inject it either.

**Comment by rwjblue** [comment]
Hmm. It should be working. Can you make a demo repo that I can use to track down the issue your are seeing?

**Comment by devinus** [comment]
@rwjblue To clarify, `this.inject.service('i18n')` should inject `i18n` into the component itself, so from the component `this.get('i18n)` would be the service, correct?

**Comment by rwjblue** [comment]
`this.inject.service` is only available in tests, and injects the instance of `service:i18n` into the test context (not the component(s) under test).

Your component would still need `i18n: Ember.inject.service()` in it also.

**Comment by devinus** [comment]
That was my problem then--a misunderstanding. I have an application injection inject `i18n` into all components, is there no way to inject it at test time?

**Comment by rwjblue** [comment]
initializers do not run in integration tests, I suppose in general you could import the initializer function and call it from your setup/beforeEach block, but that seems much less useful.

I find using `foo: Ember.inject.service()` in my components to be much better than attempting to globally inject things into all components for a couple reasons:

* The previously mentioned issue with integration tests.  
* A large percentage of the time, you do not actually need all services in all components.
* Declaring `foo: Ember.inject.service()` inside your component definition makes it super clear where this magical `foo` property is coming from.

**Comment by rwjblue** [comment]
I'm going to close this, as I believe we are now on the same page

**Comment by devinus** [comment]
Yep, not a bug. Thanks @rwjblue

**Comment by devinus** [comment]
For posterity, another alternative is passing in the service when you call render. E.g.

```this.render(hbs`{{provider-options i18n=i18n}}`);```

**Comment by rwjblue** [comment]
Yep

**Comment by rwjblue** [comment]
Though I personally prefer to test the actual template invocation that will be used.

**Comment by devinus** [comment]
Yeah, I think I prefer just injecting it manually. I'm all for self-documenting code, and doing this in 1 line versus 2 in every test is a no brainer.
