### ISSUE TITLE
Can no longer override registry in acceptance tests

### ISSUE THREAD

**Issue by mitchlloyd** [switchfly/ember-test-helpers#124]
At one point [we could override services in acceptance tests](https://github.com/switchfly/ember-test-helpers/pull/96). Now it seems like that behavior is [no longer supported](https://github.com/switchfly/ember-test-helpers/blob/master/tests/test-module-test.js#L204): 

Is there another solution that currently works?

I'm using Ember 2.2.0 and ember-qunit 0.4.16.

**Comment by rwjblue** [comment]
@mitchlloyd - I'm not sure I follow.  The PR referenced (https://github.com/switchfly/ember-test-helpers/pull/96) made it possible to override services in unit or integration tests (not acceptance tests).  In general acceptance tests do not use this repo (or ember-qunit) at all.  The functionality in [these tests](https://github.com/switchfly/ember-test-helpers/blob/master/tests/test-module-test.js#L204-L253) are currently passing in Ember 1.11 and higher.

Can you provide me with an example of what you mean?

**Comment by mitchlloyd** [comment]
If acceptance tests don't use this library then I must be mistaken that this worked in the past. I'm probably just confusing this behavior with component integration tests. Closing this issue.

I would like to do something like what was shown in your "Allow overriding services/factories in the registry" PR in an acceptance test. Something like:

```
this.application.register('service:analytics', MockAnalyticsService)
```

But I'm having trouble because of the tricky registry behavior that you documented in the [commit message of that same PR](https://github.com/rwjblue/ember-test-helpers/commit/9fc3fc41ae220b6cb1a1d20557d70aac46f0592b). My workaround for now is to handle this stubbing in my production code, but if you can drop any registry knowledge bombs on me please do!

**Comment by rwjblue** [comment]
@mitchlloyd - The super crappy (but functional) workaround for this in acceptance tests is:

```js
this.application.__deprecatedInstance__.register('service:foo', Ember.Service.extend());
```

I am actively working on a better solution to bring acceptance tests back into feature parity with integration tests (seems like a constant battle back and forth :smile_cat:).

**Comment by mitchlloyd** [comment]
Thanks for that workaround. I appreciate all your hard work that makes my development experience better :+1:

**Comment by kylecoberly** [comment]
This workaround saved my bacon just now, thank you!

**Comment by johnunclesam** [comment]
Any news on this? Why in acceptance test I can't use simply:

`this.application.register("service:notifications", notificationsServiceMock)`

instead of:

`this.application.__deprecatedInstance__.register("service:notifications", notificationsServiceMock)`?

**Which is the correct way of doing this?**

**Comment by rwjblue** [comment]
My comment in https://github.com/emberjs/ember-test-helpers/issues/124#issuecomment-159145814 is still correct.

**Comment by johnunclesam** [comment]
Ok, I'm using this right now, but how to know if things in future changes? New issue in this repo to subscribe?
