### ISSUE TITLE
Return passed value from `set` and `setProperties` on integration tests

### ISSUE THREAD

**Issue by trentmwillis** [switchfly/ember-test-helpers#131]
Right now if you call `this.set()` or `this.setProperties()` in an integration test, it returns `undefined`. Can we set it up to return the passed in value instead? This would make it consistent with the methods of the same name on Ember objects.

Will open a PR if this sounds reasonable.

**Comment by rwjblue** [comment]
:+1: - Tested PR definitely welcome.
