### ISSUE TITLE
Check Ember.Test.waiters in wait helper

### ISSUE THREAD

**Issue by adamjmcgrath** [switchfly/ember-test-helpers#139]
Hypothetically - if I created a PR to add the `Ember.Test.waiters` check in:
https://github.com/emberjs/ember.js/blob/master/packages/ember-testing/lib/helpers.js#L197
To the wait helper:
https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/wait.js#L30
Might that be accepted - or is there a reason why it doesn't include that check?

**Comment by rwjblue** [comment]
Seems like a good idea. I'm happy to help provide guidance if needed...

**Comment by adamjmcgrath** [comment]
Thanks - I'll prepare a PR

**Comment by adamjmcgrath** [comment]
Released in [v0.5.21](..//releases/tag/v0.5.21) - thanks
