### ISSUE TITLE
Global DS with Ember Data 2.3

### ISSUE THREAD

**Issue by cspanring** [switchfly/ember-test-helpers#140]
The default model unit tests in a new Ember project with Ember Data 2.3...

    ember new testproject
    ember g model post
    ember test

...will fail with...

    Promise rejected before it exists: DS is not defined@ 72 ms
    Source: 	
        ReferenceError: DS is not defined at Klass.setupModel (http://localhost:7357/assets/test-support.js:6807:26)

...which points to https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/test-module-for-model.js#L23

I'm posting it here because this is where the exception points to, but I'm not sure if this issue should be resolved on the Ember Data, Shim or CLI, etc. level.

**Comment by pangratz** [comment]
I think this should be fixed with #138...

**Comment by cspanring** [comment]
Great, thanks!

**Comment by seawatts** [comment]
Also having this issue.

**Comment by cspanring** [comment]
Seems to be resolved in Ember-CLI 2.3 (with ED 2.3.3 and Ember 2.3)
