### ISSUE TITLE
Minor version 0.5.24 -> 0.5.25 broke my tests

### ISSUE THREAD

**Issue by leepfrog** [switchfly/ember-test-helpers#159]
Not sure what the root cause is yet -- beginning to diagnose now.  Reporting in case others come across the same issue.

**Comment by leepfrog** [comment]
Also, should be noted that ember-qunit@0.4.20 does not hard-lock the version, so this made tests magically fail on travis (since we do not cache dependencies)

**Comment by leepfrog** [comment]
Looks like the new version returns this dom:
```
<div id='"ember-testing" class="ember-application">
  <div id="ember266" class="ember-view">
    <div> ....(my component).... </div>
  </div>
</div>
```

Old version returned this dom:
```
  <div id="ember266" class="ember-view">
    <div> ....(my component).... </div>
  </div>
```

Tests fail because we were using `this.$().children()` to get the child of the test container (aka component).  I assume this isn't expected / the correct practice to follow?

**Comment by rwjblue** [comment]
@leepfrog - Sorry about the breakage here.  Looking now...

**Comment by rwjblue** [comment]
Sorry for the issues, #160 should have fixed that regression (and added a test to help ensure we don't regress this again).

ember-test-helpers@0.5.26 is released...

**Comment by leepfrog** [comment]
Thanks for the fast followup @rwjblue!
