### ISSUE TITLE
Reset test elements instead of emptying them

### ISSUE THREAD

**Issue by trentmwillis** [switchfly/ember-test-helpers#178]
In our test suite we have a need to set some content in `#ember-testing` before our tests are run. This works fine for the first test, but after any test that uses `moduleFor`, that content is removed as part of [`teardownTestElements`](https://github.com/switchfly/ember-test-helpers/blob/128589b2f9ab185b2b6db65810e8406449defdf9/lib/ember-test-helpers/abstract-test-module.js#L138).

Instead of completely emptying the `#ember-testing` element, I think it would be better to cache the initial state of the element in `setupTestElements` and restore it in `teardownTestElements`.

cc @sangm

**Comment by rwjblue** [comment]
Hmm.  I'm not sure of the right path forward here.  `#ember-testing` is intended to be functionally similar to `#qunit-fixture`, where the actual element is completely controlled by the testing harness/framework.

I suspect using `QUnit.testStart` to setup your desired `ember-testing` element contents would be a good work around for now (maybe that is good enough? I dunno).

**Comment by rwjblue** [comment]
Welp: https://github.com/jquery/qunit/blob/e2b38da0be2ab4dc6fe548910fe5f71c55321f95/runner/fixture.js#L13-L25

**Comment by rwjblue** [comment]
I think this is good then, following along like the link above should work well.

**Comment by sangm** [comment]
So, the issue at hand is that in testing, rootElement is set to `ember-testing`, and putting divs inside anything else won't let the events hash trigger...

**Comment by rwjblue** [comment]
Closed by #180
