### ISSUE TITLE
isolated-container depends on private view

### ISSUE THREAD

**Issue by habdelra** [switchfly/ember-test-helpers#30]
The isolated-container depends on a private view: `Ember._MetamorphView`

https://github.com/switchfly/ember-test-helpers/blob/master/lib/ember-test-helpers/isolated-container.js#L64

This private view is no longer available as of this PR https://github.com/emberjs/ember.js/pull/10670

**Comment by rwjblue** [comment]
:+1: - looking into it now

**Comment by rwjblue** [comment]
https://github.com/emberjs/ember.js/pull/10729 reverts the change in Ember.  We will still need to come up with a path forward so that these can be removed in 2.0, but I'd prefer to do that thinking with a green test suite.

**Comment by rwjblue** [comment]
Fixed upstream for now.
