### ISSUE TITLE
Feature request: support for block-params

### ISSUE THREAD

**Issue by jamesarosen** [switchfly/ember-test-helpers#40]
I have a component that yields block-params. That is, its template has `{{yield something}}` and it is used like
```hbs
{{#my-component as |x|}}
  Use {{x}} somehow.
{{/my-component}}
```
I can't use `test-module-for-component` (or ember-qunit's `moduleForComponent`) because I need the `as |x|` in the *invocation* of `my-component`.

The only solution I've come up with is writing an integration test that compiles a template and renders an `Ember.View`. (And I actually haven't gotten that working yet, but suspect I could.)

**Comment by rwjblue** [comment]
We are working on (and nearly finished with) new test helpers exactly for this purpose. There are a couple remaining problem (like inline template precompilation without introducing production test issues with the template compiler present in tests and naming).

**Comment by rwjblue** [comment]
See discussion in https://github.com/switchfly/ember-test-helpers/pull/38 for current status (mostly agreed upon).

**Comment by ef4** [comment]
[Here's what the new-style tests look like](https://github.com/ef4/liquid-fire/blob/new-test-helpers/tests/integration/helpers/liquid-if-test.js).

**Comment by rwjblue** [comment]
Closing, as I believe this has landed and is working pretty well.
