### ISSUE TITLE
TestModuleForComponent, integration: true, and {{link-to}} incompatible

### ISSUE THREAD

**Issue by jamesarosen** [switchfly/ember-test-helpers#41]
I have a very simple component:
```hbs
{{#if (some-helper-that-relies-on-the-session)}}
  {{#link-to 'index'}}Home{{/link-to}}
{{/if}}
```
and a very simple test:
```js
componentTest('home-link', 'HomeLinkComponent', {
  integration: true,

  beforeEach: function() {
    App = startApp();
    component = this.subject();
    this.render();
  },

  afterEach: function() {
    Ember.run(App, 'destroy');
    App = null;
  }
});

test('anything, really', function(assert) {
  assert.ok(true);
});
```

With those three factors together, I get `Cannot read property 'recognizer' of undefined` and `Something you did caused a view to re-render after it rendered but before it was inserted into the DOM.`

If I remove the link, the test passes. If I turn off `integration: true`, the test passes.

In this case, I need `integration: true` because the helper requires the basic app infrastructure.

**Comment by jamesarosen** [comment]
This seems related to https://github.com/eviltrout/ember-performance/issues/34

**Comment by jamesarosen** [comment]
I've opened https://github.com/ember-cli/ember-cli/issues/3995 as a possible solution since it doesn't seem to me that `TestModuleForComponent` should really be responsible for starting routing.

**Comment by jamesarosen** [comment]
It's possible this will be -- or could be -- resolved by #38.

**Comment by technomage** [comment]
Still seeing this after the merge of #38.

**Comment by mitchlloyd** [comment]
Just a note that this issue with `{ integration: true }` and `{{link-to}}` remains after the merge of #49.

**Comment by rwjblue** [comment]
@mitchlloyd - Yep, I tested just a bit ago.  It is getting closer though.... :smile:

**Comment by jeremywrowe** [comment]
I am seeing the same thing with `{ integration: true }` `{{input}}`

here is the error:
```
Uncaught Error: Assertion Failed: HTMLBars error: Could not find component named "-text-field" (no component or template with that name was found)
```

Hope it helps. I am very excited to see this style of testing for components moving forward!

**Comment by MattMSumner** [comment]
I ran into this today. Adding `import Router from '../../router'`fixed it. Is this expected?

**Comment by MattMSumner** [comment]
Is there a solution for this yet? I'm loving `{ integration: true }` component tests but also using `link-to`.

**Comment by rwjblue** [comment]
Should be working with beta of ember and 0.4.0 of ember-qunit

**Comment by MattMSumner** [comment]
Thanks! For anyone curious here's the PR in Ember: https://github.com/emberjs/ember.js/pull/11522

**Comment by rwjblue** [comment]
Ok, closing for now. Happy to reopen if folks are still having an issue on 2.0.0-beta.1+.

**Comment by seanpdoyle** [comment]
I'm seeing something similar.

An `integration: true` component test, where the component has a `{{link-to "route"}}` in the template is throwing:

```
undefined is  an object (evaluating 'routerjs.applyIntent')
```

(thrown from [here](https://github.com/emberjs/ember.js/blob/49d58530527c9025b4bafe4f937b0c78cfe3818e/packages/ember-routing/lib/system/router.js#L874))

```js
function calculatePostTransitionState(emberRouter, leafRouteName, contexts) {
  var routerjs = emberRouter.router;
  var state = routerjs.applyIntent(leafRouteName, contexts);
  var handlerInfos = state.handlerInfos;
  var params = state.params;

  for (var i = 0, len = handlerInfos.length; i < len; ++i) {
    var handlerInfo = handlerInfos[i];
    if (!handlerInfo.isResolved) {
      handlerInfo = handlerInfo.becomeResolved(null, handlerInfo.context);
    }
    params[handlerInfo.name] = handlerInfo.params;
  }
  return state;
}
```

It looks like `emberRouter.router` is undefined.

**Comment by rwjblue** [comment]
What Ember version? This is fixed in the beta channel (but won't be back ported to 1.13 most likely).

**Comment by seanpdoyle** [comment]
@rwjblue in both `1.13.2` and `2.0.0-beta.1`

**Comment by thec0keman** [comment]
We had similar issues on `1.13.2`, and used this hack:
```
Ember.Router.reopen({
  generate: function () {
    if (!this.router)
      return;
    this._super.apply(this, arguments);
  },

  _prepareQueryParams: function () {
    if (!this.router)
      return;
    this._super.apply(this, arguments);
  }
})
```

That, plus the patch that is on `2.0-beta` and all tests are passing.

**Comment by seanpdoyle** [comment]
@thec0keman tried that out to no avail. :disappointed:

**Comment by rwjblue** [comment]
@seanpdoyle - I think the fix landed after 2.0.0-beta.1, so you'll have to test in the latest beta builds (`bower install --save ember#beta`).

**Comment by rwjblue** [comment]
The fixes needed have been pulled into release channel, and will be included in 1.13.3.

Thanks to @nathanhammond and @tomdale for making this happen.

**Comment by givanse** [comment]
For anyone reading, I was seeing this error with the following combination:

* ember-cli 1.13.1
* ember 0.12.0
* ember-data 1.0.0-beta.18

(gradual upgrade of  an app)

Downgraded `ember-qunit` to `0.3.4` and all is good.

**Comment by blimmer** [comment]
@rwjblue is there any chance that the fixes needed to make integration testing of `{{link-to}}` available in 1.12.x ? I have a project that I'm stuck on 1.12 and would love to be able to use integration test components with link-to's.

**Comment by blimmer** [comment]
I've opened [this issue](https://github.com/emberjs/ember.js/issues/11825) asking to get this functionality into 1.12.x.

**Comment by alexlafroscia** [comment]
@blimmer Thanks for that PR and for providing the Bower info, that's exactly what I needed!
