### ISSUE TITLE
Accessing store and other services from

### ISSUE THREAD

**Issue by WooDzu** [switchfly/ember-test-helpers#50]
I'm trying to write an integration test for a component which touches the store service like this:

```js
moduleForComponent('my-cool-component', {
  integration: true,
  beforeEach: function() {
    this.registry.injection('component:my-cool-component', 'store', 'service:store');
  }
});

test('Can load saved state', function(assert) {
  assert.expect(1);

  this.render(`
    {{my-cool-component}}
  `);

  assert.ok(false);
  stop();
});
```
What I'm getting is:
`at Object.TestLoader.loadModules (http://127.0.0.1:4200/assets/test-loader.js:21:18): Attempting to inject an unknown injection: `service:store`

Is this supported at all or am I missing something?

**Comment by rwjblue** [comment]
My latest PR should address this, and make sure that the store is available in this case. Needs review by @dgeb though to vet it...


As an aside: You shouldn't use initializer style injections for this (use Ember.inject.service() in the component).

**Comment by WooDzu** [comment]
Thank you for the note about `Ember.inject.service()`. That's corrected and the  `DS._setupContainer(this.registry)` workaround from another post does actually work for now.
I'll look forward to the merge!

A side question: What's the recommended way to push a model to the context of component test, eg:
```
test('Can process subgroups', function(assert) {

  this.set('groupModel', GroupModel.create({id: 1}));
  this.render(`
    {{subgroups-of group=groupModel}}
  `);

  assert.ok(false);
});
```

**Comment by WooDzu** [comment]
Nice work fixing this, I own you :beers:
