### ISSUE TITLE
remove dependency on klassy, prefer raw JS or core-object

### ISSUE THREAD

**Issue by stefanpenner** [switchfly/ember-test-helpers#56]
cc @dgeb

**Comment by rwjblue** [comment]
Why?

**Comment by stefanpenner** [comment]
why not?

**Comment by stefanpenner** [comment]
It's another dep, that does the same thing as other stuff we already have. Seems strange to add yet another object model.

Ultimately, if it was published to NPM it would be more reasonable.

**Comment by rwjblue** [comment]
> why not?

Because we have something that works here, and a bunch of other things that are actually broken we could put our times into...

**Comment by dgeb** [comment]
One of the reasons I wrote klassy.js was to have an object model in which classes could take constructor arguments. This capability is used to good effect in ember-test-helpers.

I'd be glad to publish to npm. Do either of you publish ES6-module-only libs to npm (i.e. without transpiled builds)? Looking for some conventions to follow...

**Comment by dgeb** [comment]
Alright - I've published klassy to npm: https://www.npmjs.com/package/klassy

This is something I've meant to do anyway, so thanks for the push.

Sooo... `ember-test-helpers` itself is only published to bower, and it's published without a build step, and klassy is currently a _bower_ dependency. What is the ideal configuration you're looking for here?

**Comment by stefanpenner** [comment]
> Sooo... ember-test-helpers itself is only published to bower, and it's published without a build step, and klassy is currently a bower dependency. What is the ideal configuration you're looking for here?

the goal is 100% NPM installs to enable the cut over from bower.

cc @chadhietala

**Comment by dgeb** [comment]
> the goal is 100% NPM installs to enable the cut over from bower.

by June 12?

**Comment by chadhietala** [comment]
@dgeb Negative.

**Comment by stefanpenner** [comment]
> the goal is 100% NPM installs to enable the cut over from bower.
> by June 12?

by asap :P

**Comment by dgeb** [comment]
Since klassy is no longer a blocker here, I'm closing in favor of #58.
