### ISSUE TITLE
Component integration tests used deprecated Ember.View

### ISSUE THREAD

**Issue by ef4** [switchfly/ember-test-helpers#59]
Ember has deprecated all use of `Ember.View`, which is used in (at least) component integration test setup.

I can probably work on this later today.

**Comment by toranb** [comment]
@ef4 I just noticed this today using ember 1.13.3/1.13.4

Any chance this is a simple update/bump?

**Comment by ef4** [comment]
The original issue I mentioned above got fixed via #60, #61, and #62, and at the time those were sufficient to get us running cleanly against Ember 1.13. But more deprecations have landed in Ember now.

**Comment by toranb** [comment]
Not a problem - just curious what I can do to help/what your timeline was to resolve this/what might be coming in the 1.13.5 release that we should think about as we fix this

thanks again for all your great work on this project! I get a ton of value from it :)

**Comment by blimmer** [comment]
With 2.0.0-beta.3, this causes test failures (as [seen here](https://travis-ci.org/jamesarosen/ember-i18n/jobs/71709635))

**Comment by rwjblue** [comment]
Confirm, this has jump into *big deal* territory now...

**Comment by rwjblue** [comment]
Fixed by https://github.com/switchfly/ember-test-helpers/pull/79, https://github.com/switchfly/ember-test-helpers/pull/80, and https://github.com/switchfly/ember-test-helpers/pull/81.
